name: run entry points

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip!=22.1.*
        python -m pip install --upgrade wheel setuptools
        python -m pip install --upgrade .
    - name: Run entry points
      run: |
        yaqd-bronkhorst-mfc-flow-bus --version
        yaqd-bronkhorst-mfc-flow-bus --help
        yaqd-bronkhorst-mfc-rs232 --version
        yaqd-bronkhorst-mfc-rs232 --help
